sudo: false
language: c

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- sudo apt-get -qq update
- sudo apt-get install 

script:
- stack --no-terminal setup
- stack --no-terminal build
- stack --no-terminal test

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
