sudo: false
language: c

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- export PATH=/opt/ghc/7.10.3/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

services:
-  mysql

before-script:
- mysql -e 'create database hastings;'

script:
- stack --no-terminal setup
- stack --no-terminal build
- stack --no-terminal test

cache:
  directories:
  - $HOME/.stack
  - $HOME/.ghc
  - $HOME/.local/bin

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.3
