flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/valderman/haste-standalone
    commit: bbd2641
system-ghc: true
extra-deps:
- tar-0.5.0.1
- HTTP-4000.2.23
- cereal-0.4.1.1
- shellmate-0.2.3
- ghc-simple-0.3
- data-embed-0.1.0.0
- haste-compiler-0.5.4
resolver: lts-5.2
